# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/transporthc_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=240903
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server Port (Optional, default is 8080)
server.port=8080

# Secret key
jwt.secret.key=P22Zg4MSvKsDboIU0z3I8Py0mc7LyinVik9eKGFhM6Z/X3mSXQcLee5pCG6cFmdEWs4w8d9zYZAPM2PxSS/eJA==

# logging.level.org.springframework=DEBUG
# logging.level.org.hibernate=DEBUG

